using System.Text;
using VibeWars.Models;

namespace VibeWars.Reports;

/// <summary>
/// Generates a single-image SVG debate summary card for social sharing.
/// </summary>
public static class DebateCardGenerator
{
    public static string GenerateSvg(
        DebateSession session,
        double eloA = 1200, double eloB = 1200,
        int roundsA = 0, int roundsB = 0,
        string? highlightQuote = null)
    {
        var winner = session.OverallWinner ?? "Tie";
        var winnerColor = winner.Contains("Bot A") ? "#4a9eff"
            : winner.Contains("Bot B") ? "#4aff8a" : "#888";
        var topicTrunc = session.Topic.Length > 60 ? session.Topic[..57] + "..." : session.Topic;
        var quoteTrunc = highlightQuote != null
            ? (highlightQuote.Length > 120 ? highlightQuote[..117] + "..." : highlightQuote)
            : "";

        return $"""
        <svg xmlns="http://www.w3.org/2000/svg" width="600" height="340" viewBox="0 0 600 340">
          <defs>
            <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stop-color="#1a1a2e"/>
              <stop offset="100%" stop-color="#0f0f0f"/>
            </linearGradient>
          </defs>
          <rect width="600" height="340" rx="16" fill="url(#bg)"/>
          <text x="30" y="40" fill="#e94560" font-family="sans-serif" font-size="18" font-weight="bold">VibeWars</text>
          <text x="30" y="70" fill="#e0e0e0" font-family="sans-serif" font-size="14">{EscapeSvg(topicTrunc)}</text>
          <line x1="30" y1="85" x2="570" y2="85" stroke="#333" stroke-width="1"/>
          <text x="30" y="115" fill="#4a9eff" font-family="sans-serif" font-size="13">Bot A</text>
          <text x="30" y="135" fill="#aaa" font-family="sans-serif" font-size="11">ELO {eloA:F0} | Rounds: {roundsA}</text>
          <text x="320" y="115" fill="#4aff8a" font-family="sans-serif" font-size="13">Bot B</text>
          <text x="320" y="135" fill="#aaa" font-family="sans-serif" font-size="11">ELO {eloB:F0} | Rounds: {roundsB}</text>
          <text x="300" y="175" fill="{winnerColor}" font-family="sans-serif" font-size="22" font-weight="bold" text-anchor="middle">{EscapeSvg(winner)}</text>
          <text x="300" y="195" fill="#888" font-family="sans-serif" font-size="11" text-anchor="middle">{session.StartedAt:yyyy-MM-dd} | {EscapeSvg(session.Format)} | {EscapeSvg(session.Complexity)}</text>
          {(string.IsNullOrEmpty(quoteTrunc) ? "" : $"""
          <rect x="30" y="215" width="540" height="60" rx="8" fill="#141414" stroke="#333" stroke-width="1"/>
          <text x="45" y="240" fill="#ccc" font-family="sans-serif" font-size="11" font-style="italic">"{EscapeSvg(quoteTrunc)}"</text>
          """)}
          <text x="300" y="320" fill="#555" font-family="sans-serif" font-size="10" text-anchor="middle">Generated by VibeWars</text>
        </svg>
        """;
    }

    public static string GenerateText(DebateSession session, int roundsA, int roundsB)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"  VibeWars Debate Card");
        sb.AppendLine($"  Topic: {session.Topic}");
        sb.AppendLine($"  {session.StartedAt:yyyy-MM-dd} | {session.Format} | {session.Complexity}");
        sb.AppendLine($"  Bot A: {roundsA} rounds | Bot B: {roundsB} rounds");
        sb.AppendLine($"  Winner: {session.OverallWinner}");
        return sb.ToString();
    }

    private static string EscapeSvg(string text)
        => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");
}
